assets: /storage/home/hcoda1/9/qdai41/.cache/libero/assets
bddl_files: /storage/scratch1/9/qdai41/.conda/envs/cosmos-policy/lib/python3.10/site-packages/libero/libero/bddl_files
benchmark_root: /storage/scratch1/9/qdai41/.conda/envs/cosmos-policy/lib/python3.10/site-packages/libero/libero
datasets: /storage/scratch1/9/qdai41/cosmos/LIBERO/datasets
init_states: /storage/scratch1/9/qdai41/.conda/envs/cosmos-policy/lib/python3.10/site-packages/libero/libero/init_files
